# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - calcu-later

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_fa7b6c6fbf03483db81a592abe9c5d64 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8f06365f5be2417f92594784d15ecd05 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fa7b6c6fbf03483db81a592abe9c5d64 }}/dockerized-react:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'calcu-later'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5f30cd744b17496cb337c73cefa01687 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fa7b6c6fbf03483db81a592abe9c5d64 }}/dockerized-react:${{ github.sha }}'